priv-kweihmann/oelint-adv

README.md, oelint_adv/__main__.py, oelint_adv/cls_rule.py, oelint_adv/rule_nospace_line_begin.py, oelint_adv/rule_nospace_line_cont.py, oelint_adv/rule_nospace_line_empty.py, oelint_adv/rule_nospace_line_end.py, oelint_adv/rule_notabs.py, oelint_adv/rule_var_section_lowercase.py, setup.py
- add new option for fixing some findings
automatically
Closes #19
=> Add support for auto. fixing

README.md, oelint_adv/__main__.py, oelint_adv/cls_rule.py, oelint_adv/color.py, requirements.txt
WIP for since I feel it could be better, seems to work with multiple files and the commits and messages will need amending
=> add color output option to oelint-adv

.pre-commit-hooks.yaml
Adds the required file for [pre-commit](pre-commit.com). Documentation
for this file is located here: https://pre-commit.com/#new-hooks
=> Add pre-commit hooks file

oelint_adv/__main__.py
=> fix indexing

oelint_adv/rule_base/rule_var_homepageping.py
There is already a class name VarHomepagePrefix
=> class name was already existing

README.md
Jenkins supports parsing of oelint results through warnings-ng.
=> Jenkins integration

oelint_adv/rule_base/rule_var_inconsspaces.py
Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>
=> Removed remaining of some debugging?

oelint_adv/__main__.py, oelint_adv/cls_rule.py, oelint_adv/rule_base/rule_var_multilineindent.py, oelint_adv/rule_base/rule_var_pkgspecific.py
CamelCase should be used  for classes exclusively
=> replace cammel case strings used for methods

oelint_adv/__main__.py, oelint_adv/cls_rule.py, oelint_adv/color.py, tests/test_color.py, tests/test_user_interface.py
The coloring was length and redundant. This should simplify things a bit. Test is missing for the added function. Going to add that asap.
=> simplify coloring and styling

oelint_adv/__main__.py, tests/README.md, tests/test_configfile.py
=> fix boolean deserialization in config files

.github/workflows/pythonpackage.yml
Updates `checkout` and `setup-python` actions to their latest versions.
-------------------
=> Update checkout and setup-python actions

oelint_adv/rule_base/rule_var_duplicates.py, tests/test_class_oelint_vars_duplicate.py
=> duplicates: fix to work with RDEPENDS

.github/workflows/pythonpackage.yml, setup.py
Initial steps to EOL Python 3.7 (#394).
=> EOL Python 3.7

oelint_adv/__main__.py, tests/base.py, tests/test_user_interface.py
=> rulefile: print only applicable rules

oelint_adv/cls_rule.py, tests/test_user_interface.py
and not just by line only.
Closes #420
=> main: sort findings by file and line

.github/workflows/pythonpackage.yml, setup.py
=> Add Python 3.12 CI build

oelint_adv/rule_base/rule_var_src_uri_file.py, tests/test_class_oelint_vars_srcurifile.py
=> srcurifile: skip inline blocks

README.md, oelint_adv/rule_base/rule_bbclass_exportfunctions.py, oelint_adv/rule_base/rule_bbclass_underscores.py, oelint_adv/rule_base/rule_tasks_dash.py, oelint_adv/rule_base/rule_vars_inherit_devtool.py, requirements.txt, tests/test_class_oelint_bbclass_underscore.py, tests/test_class_oelint_exportfunctions_dash.py, tests/test_class_oelint_task_dash.py, tests/test_class_oelint_var_inherit_devtool.py
=> Feat/493 Feat/500

oelint_adv/rule_base/rule_var_multilineindent.py, tests/test_class_oelint_vars_multilineident.py
=> multilineindent: fix issue with quoted values

oelint_adv/rule_base/rule_vars_variable_override.py, tests/test_class_oelint_var_override.py
=> rules: Fix override false positive

oelint_adv/tweaks.py, tests/test_class_oelint_vars_pythonpnusage.py
=> tweaks: bump release

oelint_adv/rule_base/rule_var_descriptionsame.py
=> descriptionsame: remove print

oelint_adv/rule_base/rule_vars_inherit.py, oelint_adv/rule_base/rule_vars_inherit_devtool.py, tests/test_class_oelint_var_inherit.py, tests/test_class_oelint_var_inherit_devtool.py
=> allow inherit_defer for native, nativesdk and cross

docs/wiki/oelint.file.includenotfound.md, docs/wiki/oelint.file.requirenotfound.md
=> docs: fix markdown for includenotfound and requirenotfound

oelint_adv/core.py
and write each file one by one in a sorted fashion
Relates to #585
=> core: fix write back of fixed files

oelint_adv/rule_base/rule_var_multilineindent.py
=> Add autofix for var.multilineindent

README.md, oelint_adv/rule_base/rule_var_multilineindent.py, tests/test_class_oelint_vars_multilineident.py
=> multilineident: add tests and documentation

oelint_adv/tweaks.py
=> walnascar support

oelint_adv/rule_base/rule_vars_variable_override.py, requirements.txt
=> Chore/parser 6.x

.github/workflows/pythonpackage.yml, setup.py
=> Python 3.13 support

.github/workflows/knownvar_bump.yml, scripts/bitbake-listvars, scripts/generate-knownvars
=> Priv kweihmann patch 1

.github/workflows/knownvar_bump.yml
to the known variable name action
=> ci: add all in support branches
