README.md
I made an [oelint-adv Arch Linux package](https://aur.archlinux.org/packages/oelint-adv). This is the instruction how install it from Arch Linux.
=> Add instruction to install oelint-adv from Arch Linux

oelint_adv/cls_rule.py
Importing oelint-adv as a module results in runtime errors. This modifies
the way rules are ingested to ensure that oelint-adv can be imported as
a module and not just run with the oelint-adv binary.
=> Import rules relative to base package

README.md
`id` is part of the output, but not listed in the format.
=> Add missing '[id]' to output format documentation

README.md, oelint_adv/__main__.py, tests/test_class_integration.py
Adds the `--exit-zero` argument which sets the exit code to ´0` (successful) even on found issues. Scenarios to do this are eg. CI builds where the results are evaluated in later stages.
=> --exit-zero argument to always return 0

.github/workflows/pythonpackage.yml
Builds of forks fail in the nittymcpick trigger. This PR limits the step to the main repo and skips it on forks.
=> Fix CI build for forks

oelint_adv/cls_rule.py, tests/test_class_integration.py
Noticed this while working on #235...  This is a followup for commit 41ca6cb54286 ("cls_rule: mind appendix from rule files").
A rulefile containing just an appendix rule, for example:
{
"oelint.var.mandatoryvar.DESCRIPTION": "warning"
}
would erroneously also enable all other `oelint.var.mandatoryvar` rules at their default severity.
Ref: #236
=> Fix appendix from rule files handling

oelint_adv/rule_base/rule_vars_listappend.py
For appending, you need to start with a blank, for prepending you need to end with a blank.
Followup fix for 52e7ddbc9737 ("Fix mixup in error message").
Additionally, fix this lint triggering false-positive for `FILESEXTRAPATHS`.
Fixes #238.
=> listappend: Actually fix the mixup in the lint message

oelint_adv/__main__.py, oelint_adv/cls_rule.py, tests/test_class_integration.py
Hi,
I was trying to build my own ruleset and didn't find any way to query the defaults.  So I thought it might make sense to add an option which prints the currently loaded ruleset.  This can then be used as a baseline to start customizing it...
What do you think?
=> Add --print-ruleset option

oelint_adv/cls_rule.py, tests/test_class_integration.py
When a rule's value in the rulefile is set to `""`, then the rule should use its default severity.  This behavior regressed in the last release.
Properly fall back to the default severity when `""` is found in the rulefile and add a testcase to prevent this from happening again in the future.
Fixes #241.
=> Fix default severity from rulefile

oelint_adv/__main__.py
The output of oelint-adv if no issues where displayed was still an empty line.
That made the output of e.g. 'find . -name *.bb* -exec oelint-adv --quiet --noinfo {} \;' a bit ugly.
=> No blank line if no issues are reported

README.md
The usage of full stop at end of sentences was inconsistent. I find it more natural to end all sentences with a full stop.
=> minor README cleanup

oelint_adv/rule_base/rule_var_src_uri.py, oelint_adv/rule_base/rule_var_src_uri_append.py, oelint_adv/rule_base/rule_var_src_uri_domains.py, oelint_adv/rule_base/rule_var_src_uri_file.py, oelint_adv/rule_base/rule_var_src_uri_gittag.py, oelint_adv/rule_base/rule_var_src_uri_srcrevtag.py, oelint_adv/rule_base/rule_var_src_uri_wildcard.py
A lot of single character variable names have been used. These should be fixed as it hempers reading the code a lot. A couple of fixes along the way.
=> refactor short variable names

README.md, docs/.oelint.cfg.example, oelint_adv/__main__.py, tests/test_configfile.py
add an option for the user to define an ini-style config file
in the current workspace, or HOME dir or at OELINT_CONFIG.
Parameter set in this file override the default choices from argparse
Closes #279
Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>
=> CLI: add configuration file option

.github/workflows/pythonpackage.yml
- Enable pip cache
- Remove shell override (bash is [default](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsshell) on all non-windows platforms)
=> Pip cache enabled and shell overrides removed

README.md
Adds a link to [ale](https://github.com/dense-analysis/ale), a Vim / NeoVim plugin which provides linting support.
=> Add link to Vim / NeoVim support

oelint_adv/__main__.py
ee585dca16ae07fe066c8c1154ea733e18e59a12 introduced changes that result
in an ValueError: "<filename> not in list" when sorting the filenames
at the end of the group_files function.
This reverts the resolution of f to an absolute path, which would
otherwise lead to an inconsistance as the function uses relative paths
everywhere else.
=> Keep relative path to fix ValueError when sorting by filenames

README.md
Some special characters, as the dollar symbol and the curly brackets,
can cause formatting issues if not escaped. The text then becomes
similar to an italic style, and the special characters are not shown. I
had this behaviour when opening the README.md in Firefox and Chrome.
=> README.md: escape special characters

README.md
Support was added just today to [mfussenegger/nvim-lint](https://github.com/mfussenegger/nvim-lint).
=> README: add reference to mfussenegger/nvim-lint

.github/workflows/autorelease.yml
Executes release workflow on mainline repository (= this one) only.
While the release wont hurt on forks, it'll fail always and there's not much benefit anyway.
------------------------------------------------
=> Disable release workflow on forks

oelint_adv/rule_base/rule_vars_listappend.py, tests/test_class_oelint_vars_listappend.py
When using `devtool` to modify recipes, `FILESPATH` is added to bbappend. And `FILESPATH` makes a false alarm of oelint.vars.listappend because it uses a colon as a delimiter.
=> listappend: except for FILESPATH

.bumpversion.cfg, README.md, oelint_adv/rule_base/rule_var_src_uri_checksum.py, requirements.txt, tests/test_class_oelint_vars_srcurichecksum.py
If SRC_URI has URLs pointing single file that is not from VCS, then checksusm is required
refs:
https://docs.yoctoproject.org/4.1.1/dev-manual/common-tasks.html?highlight=md5sum#fetching-code
Below fetchers recommends checksum. (def recommends_checksum return True) https://github.com/openembedded/bitbake/blob/master/lib/bb/fetch2/wget.py (http, https, ftp, ftps) https://github.com/openembedded/bitbake/blob/master/lib/bb/fetch2/s3.py (s3) https://github.com/openembedded/bitbake/blob/master/lib/bb/fetch2/sftp.py (sftp) https://github.com/openembedded/bitbake/blob/master/lib/bb/fetch2/az.py (az) - inherit wget
=> Add oelint.vars.srcurichecksum

oelint_adv/rule_base/rule_vars_listappend.py
`startswith` of String can also receive a tuple as an argument.
=> listappend: refactor code

README.md, oelint_adv/rule_base/rule_var_appendop.py, oelint_adv/rule_base/rule_var_filesextrapaths.py, oelint_adv/rule_base/rule_var_filesextrapathsop.py, oelint_adv/rule_base/rule_var_inconsspaces.py, oelint_adv/rule_base/rule_var_insaneskip.py, oelint_adv/rule_base/rule_var_src_uri_append.py, tests/test_class_oelint_var_filesoverride.py, tests/test_class_oelint_vars_appendop.py, tests/test_class_oelint_vars_fileextrapaths.py, tests/test_class_oelint_vars_fileextrapathsop.py, tests/test_class_oelint_vars_inconspaces.py, tests/test_class_oelint_vars_insaneskip.py, tests/test_class_oelint_vars_srcuriappend.py
In honister release, override syntax was changed.
However, messages and README.md are still written with the old override syntax.
Refs: https://docs.yoctoproject.org/migration-guides/migration-3.4.html#override-syntax-changes
This commit doesn't affect code behavior.
=> Change `_` to `:` in README.md and messages

oelint_adv/rule_base/rule_var_depends_ordered.py, tests/test_class_oelint_vars_dependsordered.py
as by the nature of these operations ordering will be not possible anyway
Closes #357 
Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>
=> dependsordered: ignore append and prepend ops

oelint_adv/__main__.py, tests/test_configfile.py
Add option keys `customrules` and `addrules` to convert list symbols. 
Otherwise, these options are handled as strings when added via configuration file 
This causes that the iterations in `load_rules` will be done for each character on these variables and then ignored.
=> Update list options to be usable in config file

.github/workflows/autorelease.yml
Limits the *autorelease* workflow to this repository only. It fails on forks and shouldn't run there anyway (I guess).
=> Run autorelease for mainline repo only

oelint_adv/__main__.py
Rules with '_' (underscore) in it can not be disabled via `#nooelint` (E.g. `oelint.var.suggestedvar.CVE_PRODUCT`)
Due to the regex used to identify `#nooelint` in the comment section, only rules without `underscore` can be disabled via inline comment.
If a test case is needed just let me know and I will try to come up with a testcase
=> #nooelint does not accept rules with underscores.

oelint_adv/rule_base/rule_nospace_line_end.py
If a `oelint.spaces.lineend` is find behind a `require` or `inherit` command, which `oelint-adv` can resolve, the line numbers for the `oelint.spaces.lineend` are wrongly calculated. The line number of the resulting file (with the content of the `inherit` or `require` file) is used for the finding generation.
Due to the complicated nature of the finding I didn't find any test case. 😞
=> Wrong line number behind 'inherit' or 'require' for oelint.spaces.lineend

oelint_adv/__main__.py, oelint_adv/cls_rule.py
instead of just removing things in the output, handle suppression the same way as rule files and merge them into a definitive list of what should be run.
This will also prevent that suppressed rules actually will run the fix methods but don't show output.
Closes #421
=> main: rework suppression handling

oelint_adv/__main__.py, tests/test_user_interface.py
when passing `--suppress=a --suppress=b` into
the argparse instance, we would have gotten
weird results.
Fix that and also fully support having multiple
suppression as a space separated list passed
to the parser.
To avoid future regressions a test was added.
Co-authored-by: Angelo Compagnucci angelo.compagnucci@gmail.com
=> main: fix list assembly of suppress

oelint_adv/__main__.py, tests/test_user_interface.py
In the latest rework an issues slipped in that
allowed only entire groups (or ID) to be
enabled/disabled, mind the subIDs as well when
loading the rules.
As they are filtered out afterwards it should be fine. This applies of course only to the rule itself,
thus we don't run into conflicts with the fix method call
Closes #436
=> rulefile: enabled use of subids only

oelint_adv/rule_base/rule_var_misspell.py, tests/test_class_oelint_vars_misspell.py
from SRC_URI to identify variables names.
In before this issue was also hidden due to too high confidence setting in the best match function.
Lower the confidence to 0.5 and add named resources for at leats SRCREV_{x} pattern as valid and known variables.
Closes #468
=> misspell-rule: also use named resources

README.md
Fix this issue : 
```
bitbake core-image-minial -e | grep ^MACHINEOVERRIDES | tr ':' '\n' | jq -Rn  '{replacements:{ machines: [inputs]}}' > $LAYER_PATH/.oelint-custom-machines.json
ERROR: Nothing PROVIDES 'core-image-minial'. Close matches:
core-image-minimal
core-image-minimal-dev
core-image-lsb
```
=> Fix wording in README regarding 'bitbake core-image-minimal'

oelint_adv/__main__.py
The message format is stored as a global variable, but globals are not shared between processes. Therefore, we must explicitly pass it as a parameter.
Closes #472.
This is undoubtedly an ugly solution. Please feel free to suggest more appropriate solutions. I am more than happy to assist in resolving this issue.
=> Fix messageformat not passed to thread

oelint_adv/rule_base/rule_tasks_doc_strings.py, oelint_adv/rule_base/rule_var_misspell.py, oelint_adv/rule_base/rule_var_pkgspecific.py, oelint_adv/rule_base/rule_vars_filessetting.py, oelint_adv/rule_base/rule_vars_pathhardcode.py, oelint_adv/rule_base/rule_vars_suggested.py, oelint_adv/rule_base/rule_vars_variable_override.py, tests/test_class_oelint_task_docstrings.py, tests/test_class_oelint_vars_misspell.py
=> task.docstrings: skip for __anonymous tasks

oelint_adv/rule_base/rule_var_misspell.py, tests/test_class_oelint_vars_misspell.py
so we could catch valid vars like expanded statements of SRCREV_${PN} from the extra resources list.
The error surfaced only if a named resource has the very same name as one of the valid package names.
Closes #468
=> misspell: bail out earlier for known vars

oelint_adv/rule_base/rule_var_misspell.py, tests/test_class_oelint_vars_misspell.py
=> misspell: ignore task flag statements

oelint_adv/rule_base/rule_var_misspell.py
but go back to 0.8 as a default as too many users were complaining about too many new warnings.
Value can now be controlled by env var OELINT_MISSPELL_CONFIDENCE
Closes #482
=> misspell: make confidence configurable

README.md, oelint_adv/rule_base/rule_vars_virtual.py, tests/test_class_oelint_vars_virtual.py
to check for virtual/items in RDEPENDS and
RPROVIDES
Closes #490
=> add oelint.vars.virtual rule

README.md
It was removed in 09eb6856177797fbea9a15d09bc90d4fa0495b24
=> Remove constantfile option in README

oelint_adv/rule_base/rule_var_multilineindent.py, tests/test_class_oelint_vars_multilineident.py
This PR makes the oelint.vars.multilineident check handle variables that are formatted according to [the current Yocto style guide](https://docs.yoctoproject.org/dev/contributor-guide/recipe-style-guide.html#recipe-formatting) - see #515 for discussion.
In short: if a variable is formatted like this, the current state of the linter shows a warning because the alignment of the first line is determined to be 0:
```
FOO = "this line is \
long \
"
```
The new heuristic is: iff there is non-whitespace content in the first physical line of a multi-line assignment, a variable is assumed to be aligned after the `"`. If this is the case, that point will be used as the desired indentation instead of trying to determine a best-fit indentation.
All previous formats are still accepted and tests for …
=> multilineident: Accept indentation based on non-empty first lines

oelint_adv/rule_base/rule_vars_bbclassextends.py, tests/test_class_oelint_var_bbclassextend.py
Another tiny fix/enhancement to reduce clutter in the output:
Usually, I think one would probably not try to build a -native or -nativesdk variant of an image or a packagegroup recipe. So skip this warning in these cases.
This is the same logic as in rule_file_underscores.py, which also skips these two kinds of recipes.
=> oelint.vars.bbclassextend: don't warn on image or packagegroup

README.md, oelint_adv/cls_rule.py, tests/test_user_interface.py
which prints a link to the online wiki for the particular finding. Off by default - can be enabled by running with `--messageformat="{wikiurl}"`
Closes #535
=> rule: add wikiurl message format

.github/workflows/pythonpackage.yml
This commit replaces the deprecated `setup.py` commands in the GitHub Actions CI configuration with the recommended standards-based tools. The `build` and `pip` modules are now used to build and install the package. This change aligns with the Python packaging ecosystem's move towards standardization.
Closes https://github.com/priv-kweihmann/oelint-adv/issues/543
=> Replace deprecated setup.py commands in CI

oelint_adv/rule_base/rule_var_descriptionsame.py, oelint_adv/rule_base/rule_var_descriptiontooshort.py, tests/test_class_oelint_vars_descriptionsame.py, tests/test_class_oelint_vars_descriptiontoobrief.py
by expanding the value properly before doing any check
Closes #553
=> rules: fix description rules

README.md, docs/wiki/oelint.vars.unpackdir.md, oelint_adv/rule_base/rule_vars_unpackdir.py, oelint_adv/tweaks.py, tests/test_class_oelint_vars_unpackdir.py
also adding UNPACKDIR to the list of known vars from styhead release on
Closes #568
=> rules: support for UNPACKDIR

README.md, docs/.oelint.cfg.example, oelint_adv/__main__.py, oelint_adv/cls_rule.py, oelint_adv/core.py, oelint_adv/state.py, tests/test_configfile.py, tests/test_user_interface.py
As of now only switches to hide info and warning severity messages are present.
Both locally and in CI builds it can be useful to filter findings based on the severity
of all levels.
To avoid adding two more switches, the two present switches have been
removed in favor of a generic "hide" switch to disable specified
severity level messages.
=> Add switch to hide messages of any given severity

oelint_adv/__main__.py
Always exit non-zero when issues are encountered.
In case the number of issues was 256 or its multiples, the executable
would exit `0` as values greater than 255 overflow the range of valid
exit codes (0..255).  Example:
```
$ python -c 'import sys; sys.exit(256)'; echo $?
0
```
In case of issues identified in bitbake metadata, hardcode the exit
code to 1.  Ideally the exit code should encode the type of issues
identified, for example, using the convention assumed by pylint
(https://pylint.pycqa.org/en/v3.2.3/user_guide/usage/run.html#exit-codes),
but this is not done in this change, as it requires identifying the
type of changes in the object returned by the `run` function.
Also, make the code exit according to the valid range for exit codes
and adhere to the conventions in …
=> __main__.py: Improve status report through exit codes

oelint_adv/core.py
as e.g. constantmods is expected to be a list,
but if it's set through the config file, it likely is still a string, hence the need to deserialize before applying the tweaks
Closes #635
=> core/post: deserialize all options before tweaks

oelint_adv/rule_base/rule_tasks_nopython_prefix.py
and explicitly mention that the code in the task
needs to be syntactically correct python code to
pass the check
Relates to #639
=> oelint.task.nopythonprefix: tweak message

oelint_adv/rule_base/rule_vars_multiinclude.py, requirements.txt, tests/test_class_oelint_var_multiinclude.py
and do not just look at the include name, but
at the actual file included, as they could point
to very much different files.
Fix includes a bump of the parser lib to 6.3
Closes #640
=> oelint.var.multiinclude: base rule on paths

oelint_adv/rule_base/rule_file_underscores.py, tests/test_class_oelint_file_underscores.py
The initial code is complaining about dashes in the version part of the filename for no really good reason.
Issue : https://github.com/priv-kweihmann/oelint-adv/issues/668
- [ X ] A testcase was added to test the behavior
=> oelint.file.underscores: accept dashes in version numbers

.coveragerc, .github/workflows/pythonpackage.yml, oelint_adv/rule_base/rule_func_spec.py, oelint_adv/rule_base/rule_var_spec.py, tests/test_class_oelint_func_specific.py, tests/test_class_oelint_vars_specific.py
items, as variables could be used in the expression too
=> *.specific: also probe for expanded

oelint_adv/core.py, tests/test_inlinesuppressions.py
- allow '-' in id
- rewrite filtering to allow multiple items to be mapped better to the workflow
Closes #677
=> core: fix inline suppression

README.md, oelint_adv/core.py, tests/test_class_oelint_inlinesupp.py, tests/test_inlinesuppressions.py
filter out any words that are not part of the
known IDs list and treat them as comments.
Like this further explanations can be added by the user
Closes #679
=> inline-suppressions: allow comments after ids

oelint_adv/core.py, tests/test_configfile.py
if a config file is used and a statement is
used via CLI, the config parts need to be turned into a list
Closes #681
=> core: fix config file list handling

.github/workflows/knownvar_bump.yml
to work around the issues of bitbake with ubuntu 24.04
=> ci/bump-vars: pin to ubuntu 22.04

oelint_adv/rule_base/rule_var_misspell.py, tests/test_class_oelint_vars_misspell.py
those are meant to be private/hidden, so they don't have to be checked. Also they are not exposed in the layer vars generation, leading to false positives
Closes #719
=> rules/misspell: ignore entries starting with '_'

oelint_adv/core.py
as we need to share all resources of the linter's
main process with the child tasks running the checks. Otherwise things like the CONSTANTS interface will be simply reinitialized within the child's space,
but ignoring all the added things from the tweaks
runs by the main process.
This will be mandatory from python 3.14
Closes #721
Closes #722
=> core: enforce fork as mp context

docs/wiki/oelint.vars.srcurichecksum.md, oelint_adv/rule_base/rule_var_src_uri_checksum.py, tests/test_class_oelint_vars_srcurichecksum.py
as this is long time deprecated now
Closes #757
=> oelint.vars.srcurichecksum: warn about md5sum

oelint_adv/core.py, tests/test_inlinesuppressions.py
as the latest parser will wrap comments into
blocks we need to adjust the extraction of
nooelint marker accordingly
Closes #792
=> core: fix inline supp in multiline comments
